### ISSUE TITLE
CWG ballots need proposers and endorsers

### ISSUE THREAD

**Issue by timfromdigicert** [cabforum/forum#28]
If you read the Bylaws carefully, they say the following:

" Proposing and voting on all CWG Ballots by CWG members shall follow the procedures stated in Bylaws Sec. 2.3 and 2.4 *with the exception of not requiring a proposer and endorsers*."

That is not in line with the intent or existing practice.  We should fix the Bylaws to be in line with existing practice, where all ballots have proposers and endorsers.

**Comment by dzacharo** [comment]
This change was introduced at the last revision of the Bylaws after discussion on list and at F2F meetings and the rationale was that when we do elections, the Chair (or Vice-Chair) are the ones collecting nominees and posting the elections ballot. These election ballots don't need 2 endorsers.

The entire section reads as:

> Manner of holding officer elections: If a single individual is nominated for a position, the Forum will hold a ballot prepared and submitted by the Chair, with the exception of not requiring endorsers, to confirm appointment of the nominee. 

> If more than one candidate is nominated for Chair or Vice Chair, the Chair will submit an election ballot, with the exception of not requiring endorsers, to determine which candidate will fill the position.

I am not sure what we were trying to say in 5.3.1 (3) but it seems like it was trying to say something similar regarding elections of officers for CWGs, otherwise it makes no sense... 

Thanks for spotting this. I think we should fix at the next possible update.

**Comment by dzacharo** [comment]
This issue has been addressed in Bylaws version 2.5.
